### ISSUE TITLE
White screen when running the game with imported assets

### ISSUE THREAD

**Issue by ftrotyo** [kyuuzou/warcraft#1]
Hi! Im trying to import this into unity, but im only getting a white screen. I do have war1gus and i tried to import all the assets from it into unity, but it doesnt help.I still have a white screen

**Comment by kyuuzou** [comment]
Hi! Did you follow these steps? 
1. Open the Asset Importer (Window->Warcraft Asset Importer)
2. Set the path to DATA.WAR
3. Press "Import assets" to extract the Warcraft assets
4. Close Unity
5. Revert any git changes to restore potentially removed .meta files
6. Reopen Unity, and you're all set up!

**Comment by ftrotyo** [comment]
I opened Warcraft asset importer and changed this
private string dataWarPath = string.Empty > private const string DataFile = "DATA.WAR"
I installed War1gus and imported assets
In unity there is no button that says "import assets" i have to import them manually, after i do that, nothing happens.
I tried importing them into both "root" and "warcraft resources". Neither works. I tried to refresh and restore and reimport the files multiple times and still the same issue 
 Just white screen. The menu is there, but nothing else

**Comment by kyuuzou** [comment]
The Importer is in the menu, under Window -> Warcraft Asset Importer, as per the screenshot:
![Screenshot 2022-06-23 at 22 47 37](https://user-images.githubusercontent.com/2806093/175408277-a00324d3-8b38-4e0f-ae9f-2c44ab29a901.png)

The "Import assets" button is on the Warcraft Assets Importer window:
![Screenshot 2022-06-23 at 22 47 46](https://user-images.githubusercontent.com/2806093/175408366-504619fc-ba96-46f0-9324-bdb8846dc2dd.png)

All 6 steps are very important to get the assets in the right folders, any deviation from the steps will result in the white screen, as the project won't be able to find the assets.

**Comment by ftrotyo** [comment]
Hi thank you for responding, your solution worked and now i have all assets loaded into unity
but now when i load the game by clicking on the Splash screen i still get a white screen and this error 
![image](https://user-images.githubusercontent.com/59096315/175796315-64a5ceb0-95cc-42d8-bb06-54a9ba204da9.png)
and it takes me to this line of code 
![image](https://user-images.githubusercontent.com/59096315/175796323-83529d58-ea3f-49ee-8d75-ed25f4e9863d.png)
I think it can't load the tiles for some reason. 
i tried importing both data.war from warcraft bought in GOG and from war1gus, it gives me the same error 
Would you please take a look at the code and see if there is an error? 

Or if it's more convenient to you, you could upload your version of the game that works into a google doc 

Thank you I really appreciate you getting back to me

**Comment by kyuuzou** [comment]
Looks like it can't find the assets, even though the importer put them in place. The only way I can think that can cause this without the Importer failing, is if the meta files are removed, which Unity does automatically the first time it opens. The way to restore those metas is through these steps:

4. Close Unity
5. Revert any git changes to restore potentially removed .meta files
6. Reopen Unity, and you're all set up!

I can't send you a version with the assets already there, that would be piracy.
Could you try the steps above?

**Comment by kyuuzou** [comment]
Could not reproduce.
